#export THRIFTROOT=$HOME/Hack.IBM/Thrift-ZK
export PATH=$THRIFTROOT/bin:/usr/lib/jvm/java-6-sun-1.6.0.26/bin:$PATH
export PYTHONPATH=$THRIFTROOT/lib/python2.7/site-packages:$PYTHONPATH
export PERL5LIB=$THRIFTROOT/lib/perl5:$PERL5LIB
export LD_LIBRARY_PATH=$THRIFTROOT/lib:$LD_LIBRARY_PATH
#export LD_LIBRARY_PATH=$THRIFTROOT/lib:$LD_LIBRARY_PATH
